name: .NET CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - run: docker pull camunda/zeebe:1.1.0
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - run: dotnet build --configuration Release
    - run: dotnet test