name: PREVIEW RELEASE
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9][0-9][0-9]"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:    
    - name: Pull zeebe
      run: docker pull camunda/zeebe:1.1.0
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push "Zeebe.Client.Bootstrap.${VERSION}.nupkg" --source https://nuget.pkg.github.com/arjangeertsema/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
